export const IS_PLAYING = 'IS_PLAYING'

export const UPDATE_SEQUENCES = 'UPDATE_SEQUENCES'

export const ADD_SEQUENCE = 'ADD_SEQUENCE'

export const REMOVE_SEQUENCE = 'REMOVE_SEQUENCE'

export const ADD_BARS = 'ADD_BARS'

export const REMOVE_BARS = 'REMOVE_BARS'

export const UPDATE_CURRENT_BAR = 'UPDATE_CURRENT_BAR'

export const UPDATE_CURRENT_STEP = 'UPDATE_CURRENT_STEP'

export const COPY_SEQUENCE = 'COPY_SEQUENCE'

export const PASTE_SEQUENCE = 'PASTE_SEQUENCE'

export const UPDATE_TEMPO = 'UPDATE_TEMPO'

export const UPDATE_SWING = 'UPDATE_SWING'

export const UPDATE_NUMSTEPS = 'UPDATE_NUMSTEPS'

export const UPDATE_KIT_ID = 'UPDATE_KIT_ID'

export const UPDATE_VERB_ID = 'UPDATE_VERB_ID'

export const UPDATE_KIT_BUFFERS = 'UPDATE_KIT_BUFFERS'

export const UPDATE_VERB_BUFFERS = 'UPDATE_VERB_BUFFERS'

export const IS_LOADING = 'IS_LOADING'

export const HAS_ERROR = 'HAS_ERROR'

export const DATA_LOADED = 'DATA_LOADED'

export const STORE_KITS = 'STORE_KITS'

export const STORE_VERBS = 'STORE_VERBS'

export const ADD_TRACK = 'ADD_TRACK'

export const REMOVE_TRACK = 'REMOVE_TRACK'

export const MUTE_TRACK = 'MUTE_TRACK'

export const UNMUTE_TRACK = 'UNMUTE_TRACK'

export const SOLO_TRACK = 'SOLO_TRACK'

export const UNSOLO_TRACK = 'UNSOLO_TRACK'

export const TOGGLE_SOLO_TRACK = 'TOGGLE_SOLO_TRACK'

export const UPDATE_TRACK_VOICE_ID = 'UPDATE_TRACK_VOICE_ID'

export const UPDATE_TRACK_VOLUME = 'UPDATE_TRACK_VOLUME'

export const UPDATE_TRACK_PAN = 'UPDATE_TRACK_PAN'

export const UPDATE_TRACK_REVERB_SEND = 'UPDATE_TRACK_REVERB_SEND'

export const UPDATE_TRACK_DELAY_SEND = 'UPDATE_TRACK_DELAY_SEND'

export const TRIGGERING = 'TRIGGERING'

export const AUTH_START = 'AUTH_START'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const AUTH_FAIL = 'AUTH_FAIL'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

